CREATE SEQUENCE "USUARIOS_SEQ" START WITH 1 INCREMENT BY 1;
CREATE TABLE USUARIOS(
    ID INTEGER DEFAULT NEXTVAL('USUARIOS_SEQ') NOT NULL PRIMARY KEY,
    USERNAME CHARACTER VARYING(255) NOT NULL,
    PASSWORD CHARACTER VARYING(255) NOT NULL
);
INSERT INTO USUARIOS(USERNAME, PASSWORD) VALUES ('Test1', 'test1');
INSERT INTO USUARIOS(USERNAME, PASSWORD) VALUES ('Test2', 'test2');

CREATE SEQUENCE "ESTADOS_TAREA_SEQ" START WITH 1 INCREMENT BY 1;
CREATE TABLE ESTADOS_TAREA(
    ID INTEGER DEFAULT NEXTVAL('ESTADOS_TAREA_SEQ') NOT NULL PRIMARY KEY,
    ESTADO CHARACTER VARYING(255) NOT NULL
);
INSERT INTO ESTADOS_TAREA(ESTADO) VALUES ('ACTIVO');
INSERT INTO ESTADOS_TAREA(ESTADO) VALUES ('INACTIVO');

CREATE SEQUENCE "TAREAS_SEQ" START WITH 1 INCREMENT BY 1;
CREATE TABLE TAREAS(
    ID INTEGER DEFAULT NEXTVAL('TAREAS_SEQ') NOT NULL PRIMARY KEY,
    NOMBRE CHARACTER VARYING(255) NOT NULL,
	ESTADO_TAREA_ID INTEGER NOT NULL,
	FOREIGN KEY (ESTADO_TAREA_ID) REFERENCES ESTADOS_TAREA(ID)
);	