INSERT INTO USUARIOS (username, password) VALUES ('admin','password')

INSERT INTO ESTADOS_TAREA (name,code) VALUES ('POR HACER','1001')
INSERT INTO ESTADOS_TAREA (name,code) VALUES ('EN EJECUCIÓN','1002')
INSERT INTO ESTADOS_TAREA (name,code) VALUES ('EN REVISION','1003')
INSERT INTO ESTADOS_TAREA (name,code) VALUES ('TERMINADO','1004')