CREATE TABLE  _user (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL, 
    role  varchar(255) NOT NULL, 
    UNIQUE(email)
);

CREATE TABLE  task_state (
    id bigint generated by default as identity,
    description VARCHAR(255) NOT NULL,
    UNIQUE(id)
);

insert into _user(id,name,email,password,role) values ('1','William Cabrera','wcabrera@gmail.com','$2a$10$XSPwYcRpJak4HPlbFOenPOTQ9C3Jj4P6QDTzNlburKz0cTdY2nBFy','ADMIN');


insert into task_state  (description) values ('CREATED');
insert into task_state  (description) values ('PENDING');
insert into task_state  (description) values ('IN_PROCESS');
insert into task_state  (description) values ('CANCELED');
insert into task_state  (description) values ('DERIVATIVE');
/*
   create table _task (
        status integer,
        creation_date timestamp(6),
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );


insert into _task (description,status,creation_date) values ('buy cereal',0, NOW()); 
insert into _task (description,status,creation_date) values ('study math',0, NOW());
insert into _task (description,status,creation_date) values ('save money',1, NOW());
insert into _task (description,status,creation_date) values ('buy apples',0, NOW());


*/