openapi: 3.0.1
info:
  title: Task Manager API
  description: API para gestionar tareas, usuarios y estados.
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: Autenticar usuario
      requestBody:
        description: Credenciales de usuario
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: JWT Token generado
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /tasks:
    get:
      summary: Obtener todas las tareas
      responses:
        '200':
          description: Lista de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Crear nueva tarea
      requestBody:
        description: Datos de la tarea
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Tarea creada
  /tasks/{id}:
    get:
      summary: Obtener tarea por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalles de la tarea
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    put:
      summary: Actualizar tarea
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Datos actualizados de la tarea
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Tarea actualizada
    delete:
      summary: Eliminar tarea
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Tarea eliminada
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
