// Archivo OpenAPI: openapi.yml
openapi: 3.0.1
info:
  title: Task Manager API
  description: API para gestionar tareas, usuarios y estados.
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: Autenticar usuario
      description: Permite a un usuario autenticarse y obtener un token JWT para acceder a los endpoints protegidos.
      requestBody:
        description: Credenciales de usuario
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Nombre de usuario registrado.
                password:
                  type: string
                  description: Contraseña del usuario.
      responses:
        '200':
          description: JWT Token generado
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Token JWT para autenticación.
        '401':
          description: Credenciales inválidas.

  /tasks:
    get:
      summary: Obtener todas las tareas
      description: Recupera una lista de todas las tareas registradas en el sistema.
      responses:
        '200':
          description: Lista de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: No autorizado. El token JWT es requerido.
    post:
      summary: Crear nueva tarea
      description: Permite crear una nueva tarea en el sistema.
      requestBody:
        description: Datos de la tarea
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Tarea creada
        '400':
          description: Datos inválidos en la solicitud.
        '401':
          description: No autorizado. El token JWT es requerido.

  /tasks/{id}:
    get:
      summary: Obtener tarea por ID
      description: Recupera los detalles de una tarea específica por su identificador único.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la tarea.
      responses:
        '200':
          description: Detalles de la tarea
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tarea no encontrada.
        '401':
          description: No autorizado. El token JWT es requerido.
    put:
      summary: Actualizar tarea
      description: Actualiza los datos de una tarea específica por su identificador único.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la tarea.
      requestBody:
        description: Datos actualizados de la tarea
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Tarea actualizada
        '400':
          description: Datos inválidos en la solicitud.
        '404':
          description: Tarea no encontrada.
        '401':
          description: No autorizado. El token JWT es requerido.
    delete:
      summary: Eliminar tarea
      description: Elimina una tarea específica por su identificador único.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la tarea.
      responses:
        '204':
          description: Tarea eliminada.
        '404':
          description: Tarea no encontrada.
        '401':
          description: No autorizado. El token JWT es requerido.

  /estados-tarea:
    get:
      summary: Obtener todos los estados de tarea
      description: Recupera una lista de todos los estados de tarea registrados en el sistema.
      responses:
        '200':
          description: Lista de estados de tarea
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EstadoTarea'
        '401':
          description: No autorizado. El token JWT es requerido.
    post:
      summary: Crear un estado de tarea
      description: Permite registrar un nuevo estado de tarea.
      requestBody:
        description: Datos del estado de tarea
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EstadoTarea'
      responses:
        '201':
          description: Estado de tarea creado.
        '400':
          description: Datos inválidos en la solicitud.
        '401':
          description: No autorizado. El token JWT es requerido.

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          description: Identificador único de la tarea.
        nombre:
          type: string
          description: Nombre de la tarea.
        descripcion:
          type: string
          description: Descripción de la tarea.
        estado:
          $ref: '#/components/schemas/EstadoTarea'
    EstadoTarea:
      type: object
      properties:
        id:
          type: integer
          description: Identificador único del estado de tarea.
        nombre:
          type: string
          description: Nombre del estado de tarea.
