openapi: 3.1.0
info:
  title: Gestion de Tareas API
  description: API para crear, leer, actualizar y eliminar tareas
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /auth/login:
    post:
      summary: Autenticar usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Token JWT generado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /api/tareas:
    get:
      summary: Listar todas las tareas
      responses:
        '200':
          description: Lista de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tarea'
    post:
      summary: Crear una nueva tarea
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tarea'
      responses:
        '201':
          description: Tarea creada

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    Tarea:
      type: object
      properties:
        id:
          type: integer
        titulo:
          type: string
        descripcion:
          type: string
        usuarioId:
          type: integer
        estadoId:
          type: integer
