DROP TABLE IF EXISTS USUARIOS, ROLES, ESTADOS_TAREAS, TAREAS, USUARIOS_ROLES;

CREATE TABLE USUARIOS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombres VARCHAR(250) NOT NULL,
  apellido_paterno VARCHAR(250) NOT NULL,
  apellido_materno VARCHAR(250) NOT NULL,
  username VARCHAR(250) NOT NULL UNIQUE,
  password VARCHAR(250),
  enabled BOOLEAN DEFAULT TRUE
);

CREATE TABLE ROLES(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE USUARIOS_ROLES(
    usuario_id INT NOT NULL,
    FOREIGN KEY(usuario_id) REFERENCES usuarios(id),
    rol_id INT NOT NULL,
    FOREIGN KEY(rol_id) REFERENCES roles(id)
);

CREATE TABLE ESTADOS_TAREAS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(250) NOT NULL
);

CREATE TABLE TAREAS (
  tarea_id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(250) NOT NULL,
  usuario_id INT NOT NULL,
  FOREIGN KEY(usuario_id) REFERENCES usuarios(id),
  estado_tarea_id INT NOT NULL,
  FOREIGN KEY(estado_tarea_id) REFERENCES estados_tareas(id)
);