INSERT INTO USERS (USER_ID, USER_NAME, EMAIL, PASSWORD,ROLE) VALUES (-1, 'admin00', 'admin00@previred.cl', '$2a$10$5sZcL9l77RpREwiPFncpbupkbRmqPbWeH.V9erQll7xd0rFkC6OjG', 'ADMIN');
INSERT INTO USERS (USER_ID, USER_NAME, EMAIL, PASSWORD,ROLE) VALUES (-2, 'user00', 'user00@previred.cl', '$2a$10$5sZcL9l77RpREwiPFncpbupkbRmqPbWeH.V9erQll7xd0rFkC6OjG', 'USER');

INSERT INTO TASK_STATUS (TASK_STATUS_ID, TASK_STATUS_NAME) VALUES (1, 'EJECUCION');
INSERT INTO TASK_STATUS (TASK_STATUS_ID, TASK_STATUS_NAME) VALUES (2, 'PAUSA');
INSERT INTO TASK_STATUS (TASK_STATUS_ID, TASK_STATUS_NAME) VALUES (3, 'PENDIENTE');
