DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS STATES_TASK;

CREATE TABLE ROLES
(
    id   INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) UNIQUE
);

CREATE TABLE USERS
(
    id       INTEGER PRIMARY KEY AUTO_INCREMENT,
    name     VARCHAR(50),
    lastname VARCHAR(50),
    username VARCHAR(50) UNIQUE,
    password VARCHAR(100),
    email    VARCHAR(50),
    role_id  INTEGER,
    FOREIGN KEY (role_id) REFERENCES ROLES (id)
);


CREATE TABLE TASK_STATES
(
    id     INTEGER PRIMARY KEY AUTO_INCREMENT,
    status VARCHAR(50) UNIQUE
);

CREATE TABLE TASK
(
    id        INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) UNIQUE,
    status_id INTEGER,
    FOREIGN KEY (status_id) REFERENCES TASK_STATES (id)
);